### ISSUE TITLE
Fix int8 GEMM performance issue

### ISSUE THREAD

**Issue by asroy** [ROCmSoftwarePlatform/composable_kernel#138]
PR #131 add instance for int8 GEMM, but has performance issue

https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/131#issuecomment-1074418835

**Comment by rocking5566** [comment]
I found the root cause of significant drop on int8 kernel is the version of compiler.
I make some experiments between hipcc 4.4 and hipcc 5.0
 
M, N, K = 3840, 4096, 4096
hipcc 4.4.21373-f3fd5930
fp16 Perf: 1.16249 ms, 110.839 TFlops, 82.9848 GB/s
int8 Perf: 1.18231 ms, 108.981 TFlops, 80.7071 GB/s
 
hipcc 5.0.13601-6b731c37
fp16 Perf: 1.21054 ms, 106.439 TFlops, 79.6909 GB/s
int8 Perf: 3.27323 ms, 39.3645 TFlops, 29.1518 GB/s
 
After tracing the assembly generated from hip, I found there is vgpr spilling issue.

**Comment by asroy** [comment]
fixed
