### ISSUE TITLE
Excessive compilation time

### ISSUE THREAD

**Issue by cloudhan** [ROCmSoftwarePlatform/composable_kernel#400]
Some files take unexpected looooooooooooooooooooooooooooooooooong time to compile. It seems that they contain extremely large amount of template instantiations. For example 

https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/e1a3fff67510be2af023b31587e411230b994631/library/src/tensor_operation_instance/gpu/conv2d_fwd_bias_relu/device_conv2d_fwd_xdl_c_shuffle_bias_relu_nhwc_kyxc_nhwk_f16_instance.cpp

And it seems that clang performace degenrate quickly when it passes some threshold.

I think files like it should be splitted into multiple files to better parallelize the compilation, also avoid the clang performance degenration.

**Comment by junliume** [comment]
_I was about to post the same issue when I realized it has been created_

Another suggestion is to separate `install`, `test`, and `example`. Now at least as a dependency of MIOpen, it spent quite a long time building tests and examples while it may not be needed.

Can we make sure: that only `make check` will build all the tests and examples? Or you can add a `make example` for finer granularity

**Comment by illsilin** [comment]
CK already has a multitude of targets. For example, you can build any test individually instead of building all of them at the same time. Or, if you need to use the ckProfiler, you don't need to build tests at all.
My understanding is that you need to build CK as a dependency for some product or library. 
So the question is: which targets are you currently building and what CK functionality are you actually using? 
We can make sure that you compile only the files that are absolutely necessary.

**Comment by cloudhan** [comment]
@zjing14 @illsilin At current develop branch tip, some files are ridiculously slow to compile even in Release mode

For example,
```
device_gemm_dl_i8_i8_i8_mk_nk_mn_instance.cpp
device_gemm_dl_i8_i8_i8_km_nk_mn_instance.cpp
device_gemm_dl_i8_i8_i8_mk_kn_mn_instance.cpp
```
take hour to finish the compilation.

![image](https://github.com/ROCmSoftwarePlatform/composable_kernel/assets/1279292/d7ee2701-654f-4cb6-8a61-9403fd05588b)

To visualize the the full log, drop the json file into https://ui.perfetto.dev/ 
[compile_trace.zip](https://github.com/ROCmSoftwarePlatform/composable_kernel/files/11755501/compile_trace.zip)

**Comment by illsilin** [comment]
@cloudhan Which rocm version did you use for building CK? And which GPU_TARGETS did you use?

I am actively working with compiler team to address the build time issues. We have identified at least one major issue leading to extremely long build times for some of the instances.

**Comment by cloudhan** [comment]
It is ROCm 5.4.3 and is compiled for gfx908 and gfx90a

**Comment by illsilin** [comment]
I'm going to generate a time trace with a newer compiler and try to get a glimpse inside those instance files to see which operations are taking so long and whether it's related to the other issue we are currently trying to fix.

**Comment by illsilin** [comment]
Unfortunately, observing similar picture with the latest rocm5.7 compiler, about 2200 seconds build time for gfx90a target and 3800 seconds for gfx908;gfx90a for the device_gemm_dl_i8_i8_i8_km_nk_mn_instance.

![image](https://github.com/ROCmSoftwarePlatform/composable_kernel/assets/98187287/61d0735d-0d40-42ce-89e4-26a5da1328e2)


Getting the time report now for individual compiler steps.

**Comment by illsilin** [comment]
OK, so it appears that about 75% of the overall build time and almost 95% of the front-end stage are spent in the greedy register allocator:

   ---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
  1467.7222 ( 94.4%)   1.6671 ( 85.9%)  1469.3893 ( 94.4%)  1472.4269 ( 94.4%)  Greedy Register Allocator #2
  16.0092 (  1.0%)   0.0000 (  0.0%)  16.0092 (  1.0%)  16.0502 (  1.0%)  Nary reassociation
  12.9081 (  0.8%)   0.0030 (  0.2%)  12.9111 (  0.8%)  12.9549 (  0.8%)  Machine Instruction Scheduler
  12.3246 (  0.8%)   0.0010 (  0.1%)  12.3255 (  0.8%)  12.3523 (  0.8%)  GPU Load and Store Vectorizer
  11.0128 (  0.7%)   0.0069 (  0.4%)  11.0197 (  0.7%)  11.0489 (  0.7%)  AMDGPU DAG->DAG Pattern Instruction Selection
   9.4075 (  0.6%)   0.0024 (  0.1%)   9.4099 (  0.6%)   9.4348 (  0.6%)  Straight line strength reduction
   6.0626 (  0.4%)   0.0060 (  0.3%)   6.0685 (  0.4%)   6.0832 (  0.4%)  Global Value Numbering
   6.0458 (  0.4%)   0.0003 (  0.0%)   6.0461 (  0.4%)   6.0605 (  0.4%)  Global Value Numbering #2
   3.7382 (  0.2%)   0.0042 (  0.2%)   3.7424 (  0.2%)   3.7503 (  0.2%)  PostRA Machine Instruction Scheduler
   ...
   ===-------------------------------------------------------------------------===
                          Clang front-end time report
===-------------------------------------------------------------------------===
  Total Execution Time: 1763.2269 seconds (1767.1518 wall clock)
  
For comparison, the time spent in the greedy register allocator for the fp16 instances is just 0.7% of the front-end stage and total build time is about 100 sec.

So there's high likelihood that this problem is related to the one we're already trying to fix. It also affects exclusively dl_int8 instances, just on a different architecture.

**Comment by cloudhan** [comment]
@illsilin Is it possible to split all these huge instance libraries like https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/d3adc665819dc0535a9f710ee7b8190ce85b3245/library/src/tensor_operation_instance/gpu/gemm/CMakeLists.txt into smaller one. We (onnxruntime) don't need something like fp64 and i8 at the moment.
into something like
```
add_instance_library(device_gemm_fp64_instance ...)
add_instance_library(device_gemm_fp32_instance ...)
add_instance_library(device_gemm_fp16_instance ...)
add_instance_library(device_gemm_bf16_instance ...)
add_instance_library(device_gemm_i8_instance ...)

set(device_gemm_instance device_gemm_fp64_instance device_gemm_fp32_instance ...)
```

but you might want to also refactor the following to support it:

https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/d3adc665819dc0535a9f710ee7b8190ce85b3245/library/src/tensor_operation_instance/gpu/CMakeLists.txt#L10-L19

**Comment by illsilin** [comment]
@cloudhan We may add a cmake flag, something like "DTYPE" that could be set to any subset of "fp64;fp32;fp16;bf16;int8" to only build the instances and tests/examples for the specific data types.

**Comment by illsilin** [comment]
Hello. Good news. We have implemented an option to avoid building some of the int8 instances that caused the build times to skyrocket. Please try building the latest version of the develop branch and adding "-DDTYPES="fp16;fp32;bf16". 
You should see the build times go down to ~10-12 minutes per target.

![dtypes_build](https://github.com/ROCmSoftwarePlatform/composable_kernel/assets/98187287/61384e9f-cf40-4212-96f5-ed5fc675fb97)

**Comment by illsilin** [comment]
In addition to the DTYPES we have added a couple of new cmake flags: INSTANCES_ONLY and DL_KERNELS.
Both are set to OFF by default. Adding -DINSTANCES_ONLY=ON to your cmake command line will build just the CK library and skip all tests, examples, and ckProfiler. This is all you need to build to use CK as a dependency. Setting DL_KERNELS=ON will make sure that you build gemm_dl and batched_gemm_multi_d_dl kernels. But those kernels are only useful for Navi2x architectures. For other architectured we have much faster xdl and wmma kernels. So by default, with DL_KERNELS not set, the dl kernels won't be built and this will result in additional build times reduction by ~50%.

So with all these enhancements, you should be able to build CK library in ~6 minutes per GPU target and in ~30 minutes for all GPU targets supported by the ROCm5.6 compiler.

**Comment by duli2012** [comment]
With ROMc 5.4, the build time is still very long with all the options to reduce build time enabled. Is it because the ROMc version is too old?
here is my script:
```cmake
cmake                                                                      \
-D CMAKE_PREFIX_PATH=/opt/rocm-5.4.0             \
-D CMAKE_CXX_COMPILER=/opt/rocm-5.4.0/bin/hipcc \
-D CMAKE_BUILD_TYPE=Release                  \
-D GPU_TARGETS="gfx908;gfx90a"              \
-D INSTANCES_ONLY=ON			     \
-D DTYPES="fp32;fp16;bf16"			     \
..
```

**Comment by illsilin** [comment]
How long is "very long"? 
How many threads are you using to build?
Can you run the ninja trace to see where the time is spent?

**Comment by duli2012** [comment]
> How long is "very long"? How many threads are you using to build? Can you run the ninja trace to see where the time is spent?

it's more than 12 hours. 
I didn't explicitly set the thread number. is it one by default?

**Comment by cloudhan** [comment]
@duli2012 How many threads are you using? Are you trying to build it with any `-g` options? Based on my experience on onnxruntime ck integration, we can build the ort from bare repo in about 10min or so with 96 threads.

**Comment by illsilin** [comment]
Wow, 12 hours IS very long.

By default, if you just type "make -j ", the build will try to use $(nproc) threads, i.e., one thread per CPU core.

I recommend checking the number of CPU cores on the system where you build. We typically build with 64 threads.
You can also try to run the performance monitor on the system during the build to see how many processes are running.

Here is recent CI build for gfx908;gfx90a targets, including the int8 instances, but excluding the DL kernels: total build time is 32 minutes. With int8 and DL kernels excluded, the build time is 6 minutes.

![image](https://github.com/ROCmSoftwarePlatform/composable_kernel/assets/98187287/619148c9-64cc-4793-98a9-66ad7fcb75c6)

**Comment by duli2012** [comment]
Thanks @cloudhan @illsilin.
i just use 
/make install
would this just use only one thread?

**Comment by illsilin** [comment]
OK, that explains it. Yes, you're building with 1 thread.
Please try "make -j install".
You should see significant speed up.

**Comment by duli2012** [comment]
> OK, that explains it. Yes, you're building with 1 thread. Please try "make -j install". You should see significant speed up.

I see. Thank you!

**Comment by fxmarty-amd** [comment]
`cmake` with `-D DTYPES="fp32;fp16;bf16"` then gives me

```
CMake Error at test/data_type/CMakeLists.txt:43 (add_dependencies):
  The dependency target "test_bf8_fnuz" of target "test_fp8" does not exist.


CMake Error at test/data_type/CMakeLists.txt:42 (add_dependencies):
  The dependency target "test_fp8_fnuz" of target "test_fp8" does not exist.
```

on `main` branch. Is it expected? I am using docker & an MI250 machine.
