### ISSUE TITLE
[Quality] unused parameter 'output_index_' [-Werror,-Wunused-parameter]

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/composable_kernel#561]
https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/7494c1c611382069243709cd9eab0efb90843c7c/include/ck/tensor_operation/gpu/grid/gridwise_sparse_embeddings_forward_layernorm.hpp#L188

The above line is causing issues with compiler included in ROCm 5.4.2:
```
In file included from /home/junliu/composable_kernel/include/ck/tensor_operation/gpu/device/impl/device_sparse_embeddings_forward_layernorm.hpp:15:
/home/junliu/composable_kernel/include/ck/tensor_operation/gpu/grid/gridwise_sparse_embeddings_forward_layernorm.hpp:188:34: error: unused parameter 'output_index_' [-Werror,-Wunused-parameter]
                        [&](auto output_index_) -> auto& {
                                 ^
1 error generated when compiling for gfx908.
```
not sure how it passed CK CI tests. Do we have a static stage checking via cppcheck or clang-tidy?

**Comment by illsilin** [comment]
We didn't use Rocm5.4 or later versions with CK because of several compiler issues causing some of the tests to fail on MI100.
However, I did run CI with rocm5.4.2 just a couple of days ago and it built fine:
http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2Fcomposable_kernel/detail/develop/530/pipeline 

One of the problematic tests has failed, unfortunately.

**Comment by junliume** [comment]
@illsilin this should be from a tidy check: unused-parameter, and we treat all warnings as errors :) It should be fixed regardless of the compiler version. What do you think?

**Comment by illsilin** [comment]
I'll clean it up.
